[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-a14"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=cortex-a57"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-cpu=cortex-a7"]

[target.aarch64-unknown-linux-musl]
linker    = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-cpu=cortex-a57"]
