name: Dependabot auto merge

on:
  workflow_run:
    branches:
      - dependabot/*
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'CI'
      - 'Benchmark'
      - 'Cargo test'

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: 'dependabot*'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
